### PR TITLE
fix(whisper): show plugin-required empty state

### LINKED ISSUE #963: [Bug]:› http://127.0.0.1:3782/whisper  对话：Unknown capability: whisper_visitor. Available: ['chat', 'deep_solve', 'deep_question', 'deep_research', 'math_animator', 'visualize',   'mastery_path', 'immersive_reading']
这是个什么功能？

后端包都没有

### PR DESCRIPTION
**Pull request by evan188199-tech**
## Summary
- Check the existing `/api/v1/plugins/list` capability catalog before enabling the Whisper workspace.
- Require both plugin-provided capabilities (`whisper_visitor` and `whisper_trainee`); DeepTutor core intentionally does not implement them.
- When either capability is missing, render an actionable plugin-required state, disable seat switching/input/sending, and allow a retry after installing/enabling a plugin.
- Handle registry lookup failures explicitly instead of forwarding `Unknown capability` to the user.
- Preserve the existing two-seat flow when both capabilities are registered.

Closes #963.

## Testing
- PASS (after rebasing on current `dev`): `npm run test:node` — 598 tests passed.
- PASS (after rebasing on current `dev`): `npm run lint` — 0 errors; 56 pre-existing warnings.
- PASS: `npx tsc --noEmit`.
- PASS: focused ESLint on the changed Whisper page/helper/tests.
- PASS: `npm run i18n:parity`.
- PASS: `npm run build`.
- PASS: real browser check against a production frontend with mocked official plugin-list payloads:
  - partial catalog → plugin-required notice shown; textarea and Send disabled; Retry visible
  - complete catalog → original three-step guide shown; textarea editable; Send enabled after entering a draft

The locale conflict introduced by #903 was resolved by preserving both the new GitHub placeholders and the new Whisper strings. The pre-rebase head remains at `archive/pr-976-pre-rebase-20260824`.

### CODE REVIEW

**Comment by evan188199-tech** [comment]
Rebased onto current `dev` to clear the locale conflict introduced by #903. Both sets of upstream GitHub placeholders and this PR’s Whisper strings are retained. Local verification after rebase: 598 web Node tests passed; ESLint reported 0 errors (56 pre-existing warnings).

The previous head remains at `archive/pr-976-pre-rebase-20260824`; CI is running on `f4d931c9`.

**Comment by evan188199-tech** [comment]
Closing as superseded by `bd80a4d2` / v1.5.17, which added `/api/v1/capabilities/registered` and gates the Whisper surface when `whisper_visitor` is unavailable. Issue #963 has also been closed as completed by that implementation.

Rebasing this PR onto current `dev` would restore the removed `web/app/(workspace)/whisper/page.tsx` and duplicate the capability check through the heavier plugin-list endpoint, so I am withdrawing it rather than forcing the conflict resolution.
